name: .NET Core Build

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/45 * * * *"
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
        with:
             chrome-version: stable
        id: setup-chrome
      - run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}          

      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 7.0.203

      - name: Run Project
        run: dotnet run --project ./src/DntScreenShots/DntScreenShots.csproj
          
      - name: Push changes to repo          
        run: |      
          git config http.sslVerify false
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add publisher "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git show-ref
          git branch --verbose
          git lfs install
          git checkout main
          git add -A
          git commit -m "Automated publish"
          git pull --rebase publisher main
          git push publisher main          

      

